/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "arm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MotorData, MotorData, AUTO)


PB_BIND(MotorCommand, MotorCommand, AUTO)


PB_BIND(ArmData, ArmData, AUTO)


PB_BIND(ArmCommand, ArmCommand, AUTO)


PB_BIND(ArmData2, ArmData2, AUTO)


PB_BIND(ArmCommand2, ArmCommand2, AUTO)


PB_BIND(GripperData, GripperData, AUTO)


PB_BIND(GripperCommand, GripperCommand, AUTO)


PB_BIND(GripperData2, GripperData2, AUTO)


PB_BIND(GripperCommand2, GripperCommand2, AUTO)




