/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "arm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Position, Position, AUTO)


PB_BIND(MotorStatus, MotorStatus, AUTO)


PB_BIND(ArmData, ArmData, AUTO)


PB_BIND(ArmCommand, ArmCommand, AUTO)


PB_BIND(GripperData, GripperData, AUTO)


PB_BIND(GripperCommand, GripperCommand, AUTO)



