/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UTILS_PB_H_INCLUDED
#define PB_UTILS_PB_H_INCLUDED
#include "utils/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _BoolState {
    BoolState_BOOL_UNDEFINED = 0,
    BoolState_ON = 1,
    BoolState_OFF = 2,
    BoolState_YES = 1,
    BoolState_NO = 2,
    BoolState_OPEN = 1,
    BoolState_CLOSE = 2
} BoolState;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _BoolState_MIN BoolState_BOOL_UNDEFINED
#define _BoolState_MAX BoolState_OFF
#define _BoolState_ARRAYSIZE ((BoolState)(BoolState_OFF+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
